export const types = {
  // Signup
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILED: 'SIGNUP_FAILED',

  // Login
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  // posts
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_FAILED: 'FETCH_POSTS_FAILED',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FAILED: 'ADD_POST_FAILED',
  FETCH_SINGLE_POST_SUCCESS: 'FETCH_SINGLE_POST_SUCCESS',
  FETCH_SINGLE_POST_FAILED: 'FETCH_SINGLE_POST_FAILED'
};
